#!/usr/bin/env python3
"""
Generator for varm instruction lookup tables.

Reads include/opcode.h and generates optimized C lookup tables:
- Instruction name to opcode mapping (perfect hash)
- Condition suffix to condition code mapping

Usage:
    python3 gen_lookup_tables.py              # Generate files in default location
    python3 gen_lookup_tables.py --stdout     # Output instr_name_lookup.c to stdout
    python3 gen_lookup_tables.py --cond       # Output cond_code_lookup.c to stdout
    python3 gen_lookup_tables.py --header     # Output lookup_tables.h to stdout

Note:
    This was built with Python 3.13.11 in mind.
    At this moment, there is no guarantee that it will work with older or newer python versions.
"""

import re
import sys
import os
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent.resolve()
OPCODES_HEADER = SCRIPT_DIR.parent / "include" / "opcode.h"
DEFAULT_OUTPUT_DIR = SCRIPT_DIR.parent / "src" / "asm" / "generated"


def parse_opcode_enum():
    """Parse opcode.h and extract instruction definitions."""
    with open(OPCODES_HEADER, "r") as f:
        content = f.read()

    opcodes = {}

    pattern = r"#define\s+(OP_\w+)\s+(0x[0-9A-Fa-f]+)"
    for name, value in re.findall(pattern, content):
        if name.startswith("OP_") and name not in ("OP_MASK",):
            opcodes[name] = int(value, 16)

    pattern_enum = r"OP_(\w+)\s*=\s*(0x[0-9A-Fa-f]+)"
    in_opcode_enum = False
    for line in content.split("\n"):
        stripped = line.strip()

        if stripped.startswith("typedef enum {") or (stripped == "typedef enum {"):
            in_opcode_enum = True
            continue
        if in_opcode_enum:
            if "}" in stripped and "opcode_t" in stripped:
                break
            matches = re.findall(pattern_enum, stripped)
            for name, value in matches:
                if name not in ("MASK",):
                    opcodes[f"OP_{name}"] = int(value, 16)

    return opcodes


def fnv1a_hash(s):
    """FNV-1a hash function."""
    h = 0x811C9DC5
    for c in s.lower():
        h ^= ord(c)
        h = (h * 0x01000193) & 0xFFFFFFFF
    return h


def generate_instruction_names_c(opcodes, size=256):
    """Generate instruction name lookup table with linear probing for collision resolution."""
    items = [(name[3:].lower(), value) for name, value in opcodes.items()]

    count = len(items)
    actual_size = 256
    while actual_size < count * 2 and actual_size < 65536:
        actual_size *= 2

    mask = actual_size - 1

    lines = []
    lines.append("/* AUTO-GENERATED - DO NOT EDIT */")
    lines.append("/* Generated by: scripts/gen_lookup_tables.py */")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("#include <stddef.h>")
    lines.append("#include <strings.h>")
    lines.append('#include "lookup_tables.h"')
    lines.append("")
    lines.append("typedef struct {")
    lines.append("    const char* name;")
    lines.append("    uint8_t opcode;")
    lines.append("} instr_name_entry_t;")
    lines.append("")
    lines.append(f"#define INSTR_NAME_TABLE_SIZE {actual_size}")
    lines.append("")
    lines.append(
        "static const instr_name_entry_t INSTR_NAME_TABLE[INSTR_NAME_TABLE_SIZE] = {"
    )

    table = [(None, 0) for _ in range(actual_size)]
    for name, opcode in items:
        h = fnv1a_hash(name)
        idx = h & mask
        probe = 0
        while table[idx][0] is not None:
            probe += 1
            if probe >= actual_size:
                break
            idx = (idx + 1) & mask
        if table[idx][0] is None:
            table[idx] = (name, opcode)

    for name, opcode in table:
        if name is None:
            lines.append("    { NULL, 0 },")
        else:
            lines.append(f'    {{ "{name}", {opcode} }},')
    lines.append("};")
    lines.append("")
    lines.append("uint8_t")
    lines.append("lookup_opcode(const char* name)")
    lines.append("{")
    lines.append("    if (!name || !name[0]) return 0;")
    lines.append("    uint32_t h = 0x811c9dc5;")
    lines.append("    for (const char* p = name; *p; p++) {")
    lines.append("        h ^= (uint8_t)(*p | 0x20);")
    lines.append("        h *= 0x01000193;")
    lines.append("    }")
    lines.append(f"    uint32_t idx = h & {mask};")
    lines.append(
        "    for (uint32_t probe = 0; probe < INSTR_NAME_TABLE_SIZE; probe++) {"
    )
    lines.append("        const instr_name_entry_t* entry = &INSTR_NAME_TABLE[idx];")
    lines.append("        if (entry->name == NULL) {")
    lines.append("            return 0;")
    lines.append("        }")
    lines.append("        if (strcasecmp(entry->name, name) == 0) {")
    lines.append("            return entry->opcode;")
    lines.append("        }")
    lines.append("        idx = (idx + 1) & (INSTR_NAME_TABLE_SIZE - 1);")
    lines.append("    }")
    lines.append("    return 0;")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def generate_condition_codes_c():
    """Generate condition code lookup table."""
    lines = []
    lines.append("/* AUTO-GENERATED - DO NOT EDIT */")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("#include <stddef.h>")
    lines.append("#include <strings.h>")
    lines.append('#include "lookup_tables.h"')
    lines.append("")
    lines.append("typedef struct {")
    lines.append("    const char* suffix;")
    lines.append("    uint8_t code;")
    lines.append("} cond_code_entry_t;")
    lines.append("")
    lines.append("static const cond_code_entry_t COND_CODE_TABLE[] = {")
    lines.append('    { "eq", 0x0 }, { "ne", 0x1 },')
    lines.append('    { "cs", 0x2 }, { "hs", 0x2 },')
    lines.append('    { "cc", 0x3 }, { "lo", 0x3 },')
    lines.append('    { "mi", 0x4 }, { "pl", 0x5 },')
    lines.append('    { "vs", 0x6 }, { "vc", 0x7 },')
    lines.append('    { "hi", 0x8 }, { "ls", 0x9 },')
    lines.append('    { "ge", 0xA }, { "lt", 0xB },')
    lines.append('    { "gt", 0xC }, { "le", 0xD },')
    lines.append('    { "al", 0xE }, { "nv", 0xF },')
    lines.append('    { "", 0xE },')
    lines.append("};")
    lines.append("")
    lines.append("uint8_t")
    lines.append("parse_condition(const char* suffix)")
    lines.append("{")
    lines.append("    if (!suffix) return 0xE;")
    lines.append(
        "    for (size_t i = 0; i < sizeof(COND_CODE_TABLE)/sizeof(COND_CODE_TABLE[0]); i++) {"
    )
    lines.append("        if (COND_CODE_TABLE[i].suffix[0] == '\\0') {")
    lines.append("            if (suffix[0] == '\\0') return COND_CODE_TABLE[i].code;")
    lines.append(
        "        } else if (strcasecmp(COND_CODE_TABLE[i].suffix, suffix) == 0) {"
    )
    lines.append("            return COND_CODE_TABLE[i].code;")
    lines.append("        }")
    lines.append("    }")
    lines.append("    return 0xE;")
    lines.append("}")

    return "\n".join(lines)


def generate_header():
    """Generate lookup_tables.h header."""
    return """/* AUTO-GENERATED - DO NOT EDIT */
#ifndef LOOKUP_TABLES_H
#define LOOKUP_TABLES_H

#include <stdint.h>

/* Instruction name lookup */
uint8_t lookup_opcode(const char* name);

/* Condition code lookup */
uint8_t parse_condition(const char* suffix);

#endif
"""


def main():
    args = sys.argv[1:] if len(sys.argv) > 1 else []

    if "--stdout" in args:
        opcodes = parse_opcode_enum()
        print(generate_instruction_names_c(opcodes), end="")
    elif "--cond" in args:
        print(generate_condition_codes_c(), end="")
    elif "--header" in args:
        print(generate_header(), end="")
    else:
        DEFAULT_OUTPUT_DIR.mkdir(exist_ok=True)

        opcodes = parse_opcode_enum()

        with open(DEFAULT_OUTPUT_DIR / "instr_name_lookup.c", "w") as f:
            f.write(generate_instruction_names_c(opcodes))

        with open(DEFAULT_OUTPUT_DIR / "cond_code_lookup.c", "w") as f:
            f.write(generate_condition_codes_c())

        with open(DEFAULT_OUTPUT_DIR / "lookup_tables.h", "w") as f:
            f.write(generate_header())

        print(f"Generated {DEFAULT_OUTPUT_DIR / 'instr_name_lookup.c'}")
        print(f"Generated {DEFAULT_OUTPUT_DIR / 'cond_code_lookup.c'}")
        print(f"Generated {DEFAULT_OUTPUT_DIR / 'lookup_tables.h'}")
        print(f"Instructions: {len(opcodes)}")


if __name__ == "__main__":
    main()
